[No diff commit] MSRV linker errors
  = note: /usr/bin/ld: /home/sanket1729/elements-miniscript/target/debug/deps/libelements_miniscript-bd0d8e23a43a7eb4.rlib(elements_miniscript-bd0d8e23a43a7eb4.3nofn5mo1vwzlhoo.rcgu.o): in function `<elements_miniscript::Error as core::fmt::Display>::fmt':
          /home/sanket1729/elements-miniscript/src/lib.rs:461: undefined reference to `<secp256k1_zkp::Error as core::fmt::Display>::fmt'
          /usr/bin/ld: /home/sanket1729/elements-miniscript/target/debug/deps/libelements_miniscript-bd0d8e23a43a7eb4.rlib(elements_miniscript-bd0d8e23a43a7eb4.4si5nkxpu1ml2itu.rcgu.o):(.data.rel.ro..Lvtable.8+0x18): undefined reference to `<&'a T as core::fmt::Debug>::fmt'
          /usr/bin/ld: /home/sanket1729/elements-miniscript/target/debug/deps/libelements-f234d4d0e2999928.rlib(elements-f234d4d0e2999928.elements15.rcgu.o): in function `<&'a T as core::fmt::Debug>::fmt':
          /checkout/src/libcore/fmt/mod.rs:1849: undefined reference to `<secp256k1_zkp::Error as core::fmt::Debug>::fmt'
          collect2: error: ld returned 1 exit status

I don't have the time to investigate into these errors, but based on
- The move of rust-bitcoin to 1.41.1
- rust-elements already at 1.36
- This project still in shadows and no one is really using it